import {FilesetResolver,PoseLandmarker,DrawingUtils} from "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22-rc.20250304/+esm";
const $=id=>document.getElementById(id), qsa=s=>[...document.querySelectorAll(s)];
let pose=null,stream=null,running=false,lastVideoTime=-1,lastTs=performance.now(),frames=0,facingMode="user",side="left",exercise="elbow",reps=0,setNo=1,phase="ready",resting=false,lastRep=0,displayAngle=null,lost=0,sessionStart=null,chart=null;
const CFG={target:10,sets:3,rest:30}, VIS=.18;
const guides={elbow:["ยืนหรือนั่งให้มั่นคงและให้กล้องเห็นหัวไหล่ ข้อศอก และข้อมือ","วางแขนด้านที่เลือกให้อยู่ในภาพครบ","งอและเหยียดอย่างช้า ๆ โดยไม่ฝืนช่วงการเคลื่อนไหว"],shoulder:["ให้กล้องเห็นลำตัว หัวไหล่ และข้อศอกชัดเจน","รักษาลำตัวให้มั่นคงระหว่างยกแขน","ยกแขนในช่วงที่ทำได้โดยไม่ฝืนหรือเกิดอาการปวด"],squat:["ตั้งกล้องให้เห็นสะโพก เข่า และข้อเท้า","ยืนในท่ามั่นคงและเว้นพื้นที่รอบตัว","ย่อเข่าอย่างควบคุมและกลับสู่ท่ายืนโดยไม่รีบ"]};
const names={elbow:"งอ–เหยียดข้อศอก",shoulder:"ยกแขนบริหารหัวไหล่",squat:"ย่อเข่า"};
function toast(t){$("toast").textContent=t;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2200)}
function page(id){qsa(".page").forEach(x=>x.classList.toggle("active",x.id===id));qsa(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===id));if(id==="history")renderHistory();scrollTo(0,0)}
qsa(".nav").forEach(b=>b.onclick=()=>page(b.dataset.page));$("goTrain").onclick=()=>page("train");$("backHome").onclick=()=>page("home");qsa(".ex").forEach(c=>c.querySelector("button").onclick=()=>{exercise=c.dataset.ex;$("exercise").value=exercise;updateGuide();reset();page("train")});
function updateGuide(){exercise=$("exercise").value;$("guideList").innerHTML=guides[exercise].map(x=>`<li>${x}</li>`).join("");$("exerciseDesc").textContent=`${names[exercise]} • เป้าหมาย ${CFG.target} ครั้ง × ${CFG.sets} เซต`}
$("exercise").onchange=()=>{updateGuide();reset()};qsa(".sideBtn").forEach(b=>b.onclick=()=>{qsa(".sideBtn").forEach(x=>x.classList.remove("active"));b.classList.add("active");side=b.dataset.side});
function reset(){reps=0;setNo=1;phase="ready";resting=false;displayAngle=null;sessionStart=running?Date.now():null;ui()}
$("reset").onclick=reset;
function ui(){ $("setVal").textContent=`${setNo}/${CFG.sets}`;$("repVal").textContent=`${reps}/${CFG.target}`;$("angleVal").textContent=displayAngle==null?"--°":`${Math.round(displayAngle)}°`;$("stateVal").textContent=phase.toUpperCase()}
async function initPose(){if(pose)return;const v=await FilesetResolver.forVisionTasks("https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22-rc.20250304/wasm");pose=await PoseLandmarker.createFromOptions(v,{baseOptions:{modelAssetPath:"pose_landmarker_lite.task",delegate:"GPU"},runningMode:"VIDEO",numPoses:1,minPoseDetectionConfidence:.45,minTrackingConfidence:.45})}
async function startCamera(){try{await initPose();if(stream)stream.getTracks().forEach(t=>t.stop());stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:facingMode},width:{ideal:1280},height:{ideal:720}},audio:false});$("video").srcObject=stream;await $("video").play();running=true;sessionStart=sessionStart||Date.now();$("cameraEmpty").style.display="none";$("camActions").style.display="flex";$("liveBadge").style.display="block";$("tracking").textContent="กำลังตรวจจับท่าทาง";requestAnimationFrame(loop)}catch(e){console.error(e);toast("เปิดกล้องไม่สำเร็จ กรุณาตรวจสอบสิทธิ์กล้อง")}}
function stopCamera(){running=false;if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}$("cameraEmpty").style.display="flex";$("camActions").style.display="none";$("liveBadge").style.display="none";$("tracking").textContent="กล้องปิดอยู่"}
$("startCamera").onclick=startCamera;$("stopCamera").onclick=stopCamera;$("switchCamera").onclick=async()=>{facingMode=facingMode==="user"?"environment":"user";await startCamera()};
function angle(a,b,c){const ab=[a.x-b.x,a.y-b.y],cb=[c.x-b.x,c.y-b.y],dot=ab[0]*cb[0]+ab[1]*cb[1],m=Math.hypot(...ab)*Math.hypot(...cb);if(!m)return null;return Math.acos(Math.max(-1,Math.min(1,dot/m)))*180/Math.PI}
function triplet(lm){const L=side==="left";if(exercise==="elbow")return [lm[L?11:12],lm[L?13:14],lm[L?15:16]];if(exercise==="shoulder")return [lm[L?23:24],lm[L?11:12],lm[L?13:14]];return [lm[L?23:24],lm[L?25:26],lm[L?27:28]]}
function confident(p){return p&&Number.isFinite(p.x)&&Number.isFinite(p.y)&&(p.visibility??1)>=VIS}
function count(a,ok){if(!ok||resting||phase==="complete")return;let low,high;if(exercise==="elbow"){low=65;high=150}else if(exercise==="shoulder"){low=35;high=100}else{low=95;high=155}
if(a>=high)phase="extended";if(a<=low&&phase==="extended"&&Date.now()-lastRep>700){reps++;lastRep=Date.now();phase="flexed";if(reps>=CFG.target){if(setNo>=CFG.sets){reps=CFG.target;phase="complete"}else{setNo++;reps=0;resting=true;phase="rest";setTimeout(()=>{resting=false;phase="ready";ui()},CFG.rest*1000)}}ui()}}
async function loop(ts){if(!running)return;const v=$("video"),c=$("canvas");if(v.readyState>=2&&v.currentTime!==lastVideoTime){lastVideoTime=v.currentTime;c.width=v.videoWidth;c.height=v.videoHeight;const res=pose.detectForVideo(v,performance.now()),ctx=c.getContext("2d");ctx.clearRect(0,0,c.width,c.height);if(res.landmarks?.length){lost=0;const lm=res.landmarks[0],du=new DrawingUtils(ctx);du.drawConnectors(lm,PoseLandmarker.POSE_CONNECTIONS,{color:"#58d8ef",lineWidth:3});du.drawLandmarks(lm,{color:"#ffffff",fillColor:"#1878e8",radius:3});const [a,b,d]=triplet(lm),raw=angle(a,b,d);if(raw!=null){displayAngle=displayAngle==null?raw:displayAngle*.68+raw*.32;count(displayAngle,confident(a)&&confident(b)&&confident(d));ui()}$("tracking").textContent=`ตรวจจับ ${side==="left"?"ซ้าย":"ขวา"} • ${names[exercise]}`}else{lost++;if(lost>18){displayAngle=null;$("angleVal").textContent="--°";$("tracking").textContent="จัดตำแหน่งร่างกายให้อยู่ในภาพ"}}frames++;if(ts-lastTs>1000){$("fps").textContent=`${Math.round(frames*1000/(ts-lastTs))} FPS`;frames=0;lastTs=ts}}
requestAnimationFrame(loop)}
function profile(){return JSON.parse(localStorage.getItem("pv_profile")||'{"name":"","userId":"","note":""}')}
function history(){return JSON.parse(localStorage.getItem("pv_history")||"[]")}
$("finish").onclick=()=>{const h=history(),elapsed=sessionStart?Math.max(1,Math.round((Date.now()-sessionStart)/1000)):0,total=(setNo-1)*CFG.target+reps;h.unshift({date:new Date().toISOString(),name:profile().name||"ผู้ใช้งาน",exercise,side,sets:phase==="complete"?CFG.sets:Math.max(0,setNo-1),reps:total,seconds:elapsed});localStorage.setItem("pv_history",JSON.stringify(h.slice(0,100)));toast("บันทึกการฝึกแล้ว");page("history")};
function renderHistory(){const h=history();$("totalSessions").textContent=h.length;$("totalReps").textContent=h.reduce((s,x)=>s+(x.reps||0),0);$("totalSets").textContent=h.reduce((s,x)=>s+(x.sets||0),0);$("historyBody").innerHTML=h.length?h.slice(0,20).map(x=>`<tr><td>${new Date(x.date).toLocaleString("th-TH",{dateStyle:"short",timeStyle:"short"})}</td><td>${esc(x.name)}</td><td>${names[x.exercise]||x.exercise}</td><td>${x.side==="left"?"ซ้าย":"ขวา"}</td><td>${x.sets}</td><td>${x.reps}</td><td>${Math.floor(x.seconds/60)}:${String(x.seconds%60).padStart(2,"0")}</td></tr>`).join(""):`<tr><td colspan="7">ยังไม่มีประวัติการฝึก</td></tr>`;renderChart(h)}
function renderChart(h){const rows=h.slice(0,10).reverse();$("emptyChart").style.display=rows.length?"none":"grid";if(chart)chart.destroy();if(!rows.length)return;chart=new Chart($("historyChart"),{type:"line",data:{labels:rows.map(x=>new Date(x.date).toLocaleDateString("th-TH",{day:"numeric",month:"short"})),datasets:[{label:"จำนวนครั้ง",data:rows.map(x=>x.reps),tension:.3,fill:false}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,ticks:{precision:0}}}}})}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
$("clearHistory").onclick=()=>{if(confirm("ต้องการล้างประวัติการฝึกทั้งหมดในอุปกรณ์นี้หรือไม่?")){localStorage.removeItem("pv_history");renderHistory();toast("ล้างประวัติแล้ว")}};
$("exportCsv").onclick=()=>{const h=history();if(!h.length)return toast("ยังไม่มีข้อมูลสำหรับส่งออก");const rows=[["date","name","exercise","side","sets","reps","seconds"],...h.map(x=>[x.date,x.name,names[x.exercise],x.side,x.sets,x.reps,x.seconds])];const csv="\uFEFF"+rows.map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download="physiovision-history.csv";a.click();URL.revokeObjectURL(a.href)};
function loadProfile(){const p=profile();$("name").value=p.name;$("userId").value=p.userId;$("note").value=p.note;$("profileName").textContent=p.name||"ผู้ใช้งาน";$("avatar").textContent=(p.name||"U").trim()[0]?.toUpperCase()||"U"}
$("profileForm").onsubmit=e=>{e.preventDefault();const p={name:$("name").value.trim(),userId:$("userId").value.trim(),note:$("note").value.trim()};localStorage.setItem("pv_profile",JSON.stringify(p));loadProfile();toast("บันทึกข้อมูลผู้ใช้งานแล้ว")};
updateGuide();loadProfile();ui();